// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwwaGRcAR6g0DwOXi-gh04FkiHLcPWZWA',
    appId: '1:56049816038:web:910828b034ee40c09d0627',
    messagingSenderId: '56049816038',
    projectId: 'pinball-dev-cad6e',
    authDomain: 'pinball-dev-cad6e.firebaseapp.com',
    storageBucket: 'pinball-dev-cad6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASWRZhWaF-Bdzfdd1hz-8l1FeTKmZOgbo',
    appId: '1:56049816038:android:5ca474e692f1e2749d0627',
    messagingSenderId: '56049816038',
    projectId: 'pinball-dev-cad6e',
    storageBucket: 'pinball-dev-cad6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSq6kTqW1HS0z8lRdP-T_p_2j2AkTzbLA',
    appId: '1:56049816038:ios:00ed6252afb825fb9d0627',
    messagingSenderId: '56049816038',
    projectId: 'pinball-dev-cad6e',
    storageBucket: 'pinball-dev-cad6e.appspot.com',
    iosClientId: '56049816038-uqim7i5r4ril6munuiti03f9o3dnjrgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSq6kTqW1HS0z8lRdP-T_p_2j2AkTzbLA',
    appId: '1:56049816038:ios:00ed6252afb825fb9d0627',
    messagingSenderId: '56049816038',
    projectId: 'pinball-dev-cad6e',
    storageBucket: 'pinball-dev-cad6e.appspot.com',
    iosClientId: '56049816038-uqim7i5r4ril6munuiti03f9o3dnjrgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinball',
  );
}
